version: "3.9"

services:
  db:
    container_name: api_postgres
    image: postgres:13.0-alpine
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.api
      target: development
    command: gunicorn --bind 0.0.0.0:8000 api.wsgi:application
    volumes:
      - ./api/:/api/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    container_name: api_ngnix
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - 8000:80
    depends_on:
      - api

volumes:
  postgres_data: